import Link from "next/link";
import { PageHero } from "@/components/PageHero";
import { Icon } from "@/components/ui/Icons";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Solutions LCB à Pointe-Noire", "Découvrez les solutions de financement, Épargne et conseil & accompagnement de LCB à Pointe-Noire.", "/solutions");

export default function SolutionsPage() {
  return <><PageHero eyebrow="Solutions LCB" title="Partir du besoin, construire la bonne suite." description="LCB accompagne votre besoin, facilite l'accès à une solution adaptée et vous aide à préparer les prochaines étapes." imageSrc="/images/conseillere-dossier-bureau-plan-large.png" imageAlt="Conseillère présentant un projet à une équipe" /><section className="section" id="financement"><div className="container two-column-content"><div><p className="eyebrow">Financement</p><h2>Une solution étudiée selon votre besoin.</h2><p>LCB accompagne votre demande et facilite l&apos;accès à une solution adaptée. Des solutions peuvent être étudiées à partir de 27 000 FCFA, selon votre profil et votre besoin.</p><Link className="button button-primary" href="/contact?besoin=financement">Faire une demande</Link></div><ul className="feature-list">{["Stock et équipement", "Aménagement et trésorerie", "Opportunités et développement d'activité", "Matériel, fonds de roulement, commandes et marchés", "Projets personnels et activité complémentaire"].map((item) => <li key={item}><Icon name="check" size={19} /><span>{item}</span></li>)}</ul></div></section><section className="section section-soft" id="epargne"><div className="container about-grid"><div><p className="eyebrow">Épargne</p><h2>Préparez progressivement vos projets.</h2></div><div><p>LCB vous accompagne dans une démarche d&apos;épargne adaptée à vos objectifs. Échangez avec un conseiller pour connaître les modalités correspondant à votre situation.</p><Link className="button button-primary" href="/contact?besoin=epargne">Se renseigner sur l&apos;Épargne <Icon name="arrow" size={18} /></Link></div></div></section><section className="section" id="accompagnement"><div className="container two-column-content"><div><p className="eyebrow">Conseil & accompagnement</p><h2>Un conseiller à vos côtés.</h2><p>Un conseiller à vos côtés pour mieux structurer votre besoin et préparer les prochaines étapes.</p><Link className="button button-primary" href="/contact?besoin=accompagnement">Parler à un conseiller</Link></div><ul className="feature-list">{["Écoute", "Orientation", "Étude du besoin", "Préparation du dossier", "Accompagnement"].map((item) => <li key={item}><Icon name="check" size={19} /><span>{item}</span></li>)}</ul></div></section><section className="content-note"><div className="container"><strong>À savoir</strong><p>Toute demande fait l&apos;objet d&apos;une étude. Le dépôt d&apos;une demande ne garantit pas l&apos;obtention d&apos;un financement.</p></div></section></>;
}
